
import { ROLES } from './userRoles';

export const PERMISSIONS = {
  VIEW_LISTINGS: 'view_listings',
  CREATE_LISTING: 'create_listing',
  EDIT_LISTING: 'edit_listing',
  DELETE_LISTING: 'delete_listing',
  VIEW_ANALYTICS: 'view_analytics',
  MANAGE_TENANTS: 'manage_tenants',
  MANAGE_PAYMENTS: 'manage_payments',
  VIEW_DOCUMENTS: 'view_documents',
  SUBMIT_MAINTENANCE: 'submit_maintenance',
  INVESTMENT_TOOLS: 'investment_tools',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.AGENT]: [
    PERMISSIONS.VIEW_LISTINGS,
    PERMISSIONS.CREATE_LISTING,
    PERMISSIONS.EDIT_LISTING,
    PERMISSIONS.DELETE_LISTING,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_TENANTS,
  ],
  [ROLES.OWNER]: [
    PERMISSIONS.VIEW_LISTINGS,
    PERMISSIONS.CREATE_LISTING,
    PERMISSIONS.EDIT_LISTING,
    PERMISSIONS.MANAGE_TENANTS,
    PERMISSIONS.MANAGE_PAYMENTS,
  ],
  [ROLES.INVESTOR]: [
    PERMISSIONS.VIEW_LISTINGS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.INVESTMENT_TOOLS,
    PERMISSIONS.VIEW_DOCUMENTS,
  ],
  [ROLES.TENANT]: [
    PERMISSIONS.VIEW_LISTINGS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.SUBMIT_MAINTENANCE,
  ],
  [ROLES.BUYER]: [
    PERMISSIONS.VIEW_LISTINGS,
  ],
};